### ISSUE TITLE
Fails to compile (npm run dev)

### ISSUE THREAD

**Issue by LiFaytheGoblin** [Q42/amazeballs#1]
When I run 
`'npm install' `
in the command line, I get a bunch of warnings. When I then run
`'npm run dev'`
and go on the localhost, It says
```
ERROR in ./src/App.vue
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/lifay/werk/VueJs/amazeballs-master/node_modules/vue-loader/index.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
 @ ./src/main.js 2:0-28
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

I am using Ubuntu. I used Firefox as a browser.

**Comment by LiFaytheGoblin** [comment]
This was an issue with node.js. I was using an old version, with the new version I don't get this error anymore.
